/* Generated By:JavaCC: Do not edit this line. SqlParser.java */
package parsing;
import java.util.List;
import java.util.ArrayList;
import execution.ExecuteStatement;

public class SqlParser implements SqlParserConstants {

    private List<Object> sql = new ArrayList<Object>(); // sql�?外层语句
    private List<Object> list = new ArrayList<Object>();//
    private List<Object> templist = new ArrayList<Object>();

    public static void main(String[] args) throws Exception {
        SqlParser parser = new SqlParser(System.in);
        parser.parse();
        System.out.println("sql is correct!");


    }

  final public void parse() throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CREATE:
      //***************1	CREATE ************
          //1.1.1	CREATE DATABASE testdb�?
          t = jj_consume_token(CREATE);
      create(t);
      break;
    case DROP:
      t = jj_consume_token(DROP);
      drop(t);
      break;
    case RENAME:
      t = jj_consume_token(RENAME);
      rename(t);
      break;
    case USE:
      t = jj_consume_token(USE);
      use(t);
      break;
    case SHOW:
      t = jj_consume_token(SHOW);
      show(t);
      break;
    case SELECT:
      jj_consume_token(SELECT);
        t = new Token();
        t.image = "select";
        System.out.println(t.image);
        sql.add(t);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ALL:
      case DISTINCT:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DISTINCT:
          jj_consume_token(DISTINCT);
          break;
        case ALL:
          jj_consume_token(ALL);
          break;
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      selectResultList();
      jj_consume_token(FROM);
      fromTables();
      where();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_END:
        jj_consume_token(STATEMENT_END);
        break;
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case INSERT:
      jj_consume_token(INSERT);
      jj_consume_token(INTO);
      jj_consume_token(ID);
      jj_consume_token(VALUES);
      jj_consume_token(LBRACKET);
      jj_consume_token(NAME);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_1;
        }
        jj_consume_token(COMMA);
        jj_consume_token(NAME);
      }
      jj_consume_token(RBRACKET);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_END:
        jj_consume_token(STATEMENT_END);
        break;
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case VALUES:
      jj_consume_token(VALUES);
      jj_consume_token(LBRACKET);
      values();
      jj_consume_token(RBRACKET);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_END:
        jj_consume_token(STATEMENT_END);
        break;
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case UPDATE:
      jj_consume_token(UPDATE);
      jj_consume_token(ID);
      jj_consume_token(SET);
      sets();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHERE:
        where();
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_END:
        jj_consume_token(STATEMENT_END);
        break;
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case DELETE:
      t = jj_consume_token(DELETE);
      delete(t);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//把Token存到sql�?
  final public void saveTokenInSQL(Token a) throws ParseException {
    Token t;
        t = a;
        System.out.println(t.image+" : "+t.kind);
        sql.add(t);
  }

//把list存到sql�?
  final public void saveListInSQL(List<Object> a) throws ParseException {
        sql.add(a);
  }

//把Token存到list�?
  final public void saveTokenInList(Token a,List<Object> l) throws ParseException {
    Token t;
        t = a;
        System.out.println("------->"+t.image+" : "+t.kind);
        l.add(t);
  }

//把TempList存到list�?
  final public void saveTempListInList(List<Object> temp,List<Object> l) throws ParseException {
        //System.out.print("  list is : ");
//        for (Object object : temp)
//        {
//            System.out.println(object);
//        }
//        System.out.println("");

        l.add(temp);
  }

  final public void showStructure() throws ParseException {
        System.out.println("----------STRUCTURE----------");
        for (Object object : sql)
        {
            System.out.println(object);
        }
  }

  final public void create(Token d) throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
        t=d;
        System.out.println("------CREATE METHOD --------");
        saveTokenInSQL(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DATABASE:
      ////1.1.1	CREATE DATABASE testdb�?
                  t = jj_consume_token(DATABASE);
                saveTokenInSQL(t);
      t = jj_consume_token(ID);
                saveTokenInSQL(t);
      break;
    case TABLE:
      t = jj_consume_token(TABLE);
                saveTokenInSQL(t);
      t = jj_consume_token(ID);
                 saveTokenInSQL(t);
                 createTable();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      ExecuteStatement.createDatabase(sql);
  }

////1.1.1	CREATE TABLE table_name
//  //( 	column_name_1 data_type default value column_constraint,
//  //column_name_2 data_type default value column_constraint,
//  //...,
//  //table_constraint	 );
  final public void createTable() throws ParseException {
 Token t;
    t = jj_consume_token(TABLE);
        saveTokenInSQL(t);
  }

  final public void delete(Token d) throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
        t=d;
        System.out.println("------DELETE METHOD --------");
        saveTokenInSQL(t);
    t = jj_consume_token(FROM);
        saveTokenInSQL(t);
    t = jj_consume_token(ID);
         saveTokenInSQL(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      where();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//2.1.1	DROP DATABSE databse_name;
  final public void drop(Token d) throws ParseException {
     Token t;
     sql = new ArrayList<Object>();
         t=d;
         System.out.println("------DROP METHOD --------");
         saveTokenInSQL(t);
    t = jj_consume_token(DATABASE);
         saveTokenInSQL(t);
    t = jj_consume_token(ID);
         saveTokenInSQL(t);
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      ExecuteStatement.dropDatabase(sql);
  }

//3.1.1	RENAME DATABSE old_name TO new_name
  final public void rename(Token d) throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
         t=d;
         System.out.println("------RENAME METHOD --------");
         saveTokenInSQL(t);
    t = jj_consume_token(DATABASE);
                     saveTokenInSQL(t);
    t = jj_consume_token(ID);
                     saveTokenInSQL(t);
    t = jj_consume_token(TO);
                     saveTokenInSQL(t);
    t = jj_consume_token(ID);
                     saveTokenInSQL(t);
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          ExecuteStatement.renameDatabase(sql);
  }

//5.1.1	SHOW DATABASE;
  final public void show(Token d) throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
         t=d;
         System.out.println("------SHWO METHOD --------");
         saveTokenInSQL(t);
    t = jj_consume_token(DATABASE);
                     saveTokenInSQL(t);
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          ExecuteStatement.showDatabase(sql);
  }

//4.1.1	USE database_name
  final public void use(Token d) throws ParseException {
    Token t;
    sql = new ArrayList<Object>();
         t=d;
         System.out.println("------USE METHOD --------");
         saveTokenInSQL(t);
    t = jj_consume_token(ID);
                 saveTokenInSQL(t);
        showStructure();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STATEMENT_END:
      jj_consume_token(STATEMENT_END);
      break;
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     ExecuteStatement.useDatabase(sql);
  }

//where语句
  final public void where() throws ParseException {
 Token t;
    t = jj_consume_token(WHERE);
        saveTokenInSQL(t);
    multiCondition();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GROUP_BY:
      groupBy();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ORDER_BY:
      orderBy();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
  }

// 多条件并列的时�??
  final public void multiCondition() throws ParseException {
    Token t;
    int i = 0;// i = 0 表示只有�?个condition�?=1 表示有多个condition
    list = new ArrayList<Object>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
    case NAME:
      condition();
      break;
    case LBRACKET:
      jj_consume_token(LBRACKET);
      condition();
      jj_consume_token(RBRACKET);
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        t = jj_consume_token(AND);
                         saveTokenInList(t,list); i = 1;
        break;
      case OR:
        t = jj_consume_token(OR);
                         saveTokenInList(t,list); i = 1;
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
      case NAME:
        condition();
        break;
      case LBRACKET:
        jj_consume_token(LBRACKET);
        condition();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
        if( i == 0)
        {
           list = templist;
           saveListInSQL(list);
           System.out.println("Only one condition");
        }
        else
        {
           saveListInSQL(list);
        }
  }

//小情况；小条�?
  final public void condition() throws ParseException {
    Token t;
    templist = new ArrayList<Object>();
    name();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LIKE:
    case EQ:
    case GT:
    case LT:
    case NE:
      simpleCondition();
      break;
    case BETWEEN:
      betweenCondition();
      break;
    case IN:
      in();
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// Between ...  AND ... 条件语句
  final public void betweenCondition() throws ParseException {
 Token t;
    t = jj_consume_token(BETWEEN);
                     saveTokenInList(t,templist);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TEXT:
      t = jj_consume_token(TEXT);
                                saveTokenInList(t,templist);
      break;
    case NUMBER:
      t = jj_consume_token(NUMBER);
                                saveTokenInList(t,templist);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(AND);
                 saveTokenInList(t,templist);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TEXT:
      t = jj_consume_token(TEXT);
                                saveTokenInList(t,templist);
      break;
    case NUMBER:
      t = jj_consume_token(NUMBER);
                                saveTokenInList(t,templist);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void in() throws ParseException {
    Token t;
    // 新建�?个临时的templist1存放小括号内容（�?    --->templist1
    // a in （templiste1�?    --->condition ----> templist
    //condition存放在templist�? conditon
    //只有�?个condition的时�? list = templist
    //muticondition ---> list 放在sql�?
    List<Object>templist1 = new ArrayList<Object>();
    t = jj_consume_token(IN);
        //templist.add(t);
        saveTokenInList(t,templist);
    jj_consume_token(LBRACKET);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TEXT:
        t = jj_consume_token(TEXT);
                                 saveTokenInList(t,templist1);
        break;
      case NUMBER:
        t = jj_consume_token(NUMBER);
                                 saveTokenInList(t,templist1);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          jj_consume_token(COMMA);
          break;
        default:
          jj_la1[26] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case TEXT:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_3;
      }
    }
    jj_consume_token(RBRACKET);
            //templist.add(t);
         saveTempListInList(templist1,templist);
         saveTempListInList(templist,list);
  }

// 用于
  final public void name() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      t = jj_consume_token(NAME);
      break;
    case ID:
      t = jj_consume_token(ID);
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    //templist.add(t);
    saveTokenInList(t,templist);
  }

//�?单条�?
  final public void simpleCondition() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      t = jj_consume_token(EQ);
                        saveTokenInList(t,templist);
      break;
    case GT:
      t = jj_consume_token(GT);
                                                                              saveTokenInList(t,templist);
      break;
    case LT:
      t = jj_consume_token(LT);
                        saveTokenInList(t,templist);
      break;
    case NE:
      t = jj_consume_token(NE);
                                                                              saveTokenInList(t,templist);
      break;
    case LIKE:
      t = jj_consume_token(LIKE);
                        saveTokenInList(t,templist);
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    rightCondition();
  }

  final public void rightCondition() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TEXT:
      // �?/�? ，数字，功能
            t = jj_consume_token(TEXT);
              saveTokenInList(t,templist);
              saveTempListInList(templist,list);
      break;
    case NUMBER:
      t = jj_consume_token(NUMBER);
               saveTokenInList(t,templist);
               saveTempListInList(templist,list);
      break;
    case ID:
      function();
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//功能方法
  final public void function() throws ParseException {
 Token t;
    //  id (（多）参�? )
         t = jj_consume_token(ID);
        saveTokenInList(t,templist);
        saveTempListInList(templist,list);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      arguments();
      jj_consume_token(RBRACKET);
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
  }

//（多）参数函�?
  final public void arguments() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      argument();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[33] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        argument();
      }
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
  }

// �?组参�?
  final public void argument() throws ParseException {
 Token t;
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      jj_consume_token(STRING);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void selectResultList() throws ParseException {
 Token t;
    System.out.println("------SELECT METHOD --------");
    selectResult();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      selectResult();
    }
  }

  final public void selectResult() throws ParseException {
 Token t;
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      jj_consume_token(DOT);
      jj_consume_token(ID);
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      jj_consume_token(ID);
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
  }

  final public void fromTables() throws ParseException {
 Token t;
    table();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_6;
      }
      jj_consume_token(COMMA);
      table();
    }
  }

  final public void table() throws ParseException {
 Token t;
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      jj_consume_token(ID);
      break;
    default:
      jj_la1[40] = jj_gen;
      ;
    }
  }

//void arguments() :
//{}
//{
// (
//    argument()
//    (
//        ","
//     argument()
//    )*
// )?
//}
  final public void values() throws ParseException {
    value();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[41] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      value();
    }
  }

  final public void value() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      jj_consume_token(STRING);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void groupBy() throws ParseException {
 Token t;
    t = jj_consume_token(GROUP_BY);
                                     saveTokenInSQL(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      t = jj_consume_token(ID);
      break;
    case NAME:
      t = jj_consume_token(NAME);
      break;
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                      saveTokenInSQL(t);
  }

  final public void orderBy() throws ParseException {
 Token t;
    t = jj_consume_token(ORDER_BY);
                        saveTokenInSQL(t);
    t = jj_consume_token(ID);
                         saveTokenInSQL(t);
  }

  final public void sets() throws ParseException {
    set();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[44] = jj_gen;
        break label_8;
      }
      jj_consume_token(COMMA);
      set();
    }
  }

  final public void set() throws ParseException {
    jj_consume_token(ID);
    jj_consume_token(EQ);
    rightCondition();
  }

  /** Generated Token Manager. */
  public SqlParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[45];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static private int[] jj_la1_5;
  static private int[] jj_la1_6;
  static private int[] jj_la1_7;
  static private int[] jj_la1_8;
  static private int[] jj_la1_9;
  static private int[] jj_la1_10;
  static private int[] jj_la1_11;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
      jj_la1_init_5();
      jj_la1_init_6();
      jj_la1_init_7();
      jj_la1_init_8();
      jj_la1_init_9();
      jj_la1_init_10();
      jj_la1_init_11();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000,0x2000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10000,0x10000,0x0,0x4000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x200000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x400,0x400,0x0,0x0,0x0,0x0,0x0,0x0,0x1020,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10000400,0x0,0x0,0x0,0x0,0x0,0x0,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000,0x20000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_5() {
      jj_la1_5 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40e0,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_6() {
      jj_la1_6 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x400000,0x0,0x10800,0x0,0x0,0x400000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_7() {
      jj_la1_7 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_8() {
      jj_la1_8 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_9() {
      jj_la1_9 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80000,0x100000,0x200000,0x0,0x0,0x200000,0x7800000,0x0,0x0,0x0,0x0,0x0,0x0,0x7800000,0x0,0x200000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_10() {
      jj_la1_10 = new int[] {0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x2000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x8,0x20,0x0,0x8,0x0,0x8,0x0,0x0,0x8,};
   }
   private static void jj_la1_init_11() {
      jj_la1_11 = new int[] {0x0,0x0,0x60000,0x0,0x60000,0x60000,0x0,0x60000,0x0,0x0,0x60000,0x0,0x60000,0x60000,0x60000,0x60000,0x60000,0x0,0x0,0xc00,0x0,0x0,0xc00,0x0,0x11000,0x11000,0x0,0x11000,0x11000,0xc00,0x0,0x11400,0x0,0x0,0x400,0x9000,0x0,0x0,0x0,0x0,0x400,0x0,0x9000,0xc00,0x0,};
   }

  /** Constructor with InputStream. */
  public SqlParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SqlParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SqlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SqlParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SqlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SqlParser(SqlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SqlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[371];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 45; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
          if ((jj_la1_5[i] & (1<<j)) != 0) {
            la1tokens[160+j] = true;
          }
          if ((jj_la1_6[i] & (1<<j)) != 0) {
            la1tokens[192+j] = true;
          }
          if ((jj_la1_7[i] & (1<<j)) != 0) {
            la1tokens[224+j] = true;
          }
          if ((jj_la1_8[i] & (1<<j)) != 0) {
            la1tokens[256+j] = true;
          }
          if ((jj_la1_9[i] & (1<<j)) != 0) {
            la1tokens[288+j] = true;
          }
          if ((jj_la1_10[i] & (1<<j)) != 0) {
            la1tokens[320+j] = true;
          }
          if ((jj_la1_11[i] & (1<<j)) != 0) {
            la1tokens[352+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 371; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
